### ISSUE TITLE
Perform meta-features separation by dataset source

### ISSUE THREAD

**Issue by MorrisNein** [ITMO-NSS-team/GAMLET#29]
Since #15, meta-features cache is stored by path `data/metafeatures/*mf_source*/*dataset_id*`. 

Since datasets from different source can potentially have the same ID, the storage of meta-features needs an additional level of separation.

There are two possible ways to address this issue:

1. Add directory separation (e.g.: `data/metafeatures/*mf_source*/*dataset_source*/*dataset_id*.pkl` or `data/datasets/*dataset_source*/*dataset_id*/*mf_source*.pkl`)
2. Integrate a light-weight file database ([sqlite3](https://docs.python.org/3/library/sqlite3.html), [TinyDB](https://pypi.org/project/tinydb/), etc.).

**Comment by DRMPN** [comment]
In my opinion it is easier to do 1 way. 
There are several reasons for this:
1) Entire files shouldn't be stored in the database. (I think this is a general rule, but I could be wrong)
2) We have to do a database design.
3) We have to decide whether to use clear SQL queries in the code or use ORM like Peewee etc.
4) Database should be used to persist data, such as long-term storage.
5) Consider NOSQL solutions like Redis, I've seen it used for caching but haven't tried to understand or implement it.
