### ISSUE TITLE
fedot_pipelines_loader with FEDOT 0.7.2

### ISSUE THREAD

**Issue by ShikovEgor** [ITMO-NSS-team/GAMLET#70]
В релизе FEDOT 0.7.2 убрали fedot.core.validation.
Подскажите, плиз, как можно скорректировать следующий код:
https://github.com/ITMO-NSS-team/GAMLET/blob/069719f65ccac77d090409c1c722de0318579d9c/meta_automl/data_preparation/models_loaders/fedot_pipelines_loader.py#L13C1-L14C1

**Comment by nicl-nno** [comment]
Ты про tabular_cv_generator? Он теперь тут https://github.com/aimclub/FEDOT/blob/70fc033921805b6b348844a87727d5c82bfe75c8/fedot/core/data/cv_folds.py#L45

Т.е. будет from fedot.core.data.data_split import cv_generator. И параметр будет называться cv_folds
